POST http://localhost:8080/uk
Content-Type: application/json

{
  "name": "xxr"
}
###
PUT http://localhost:8080/uk
Content-Type: application/json

{
  "name": "tgg",
  "id":2
}
###
DELETE http://localhost:8080/uk/444
Content-Type: application/json
###
GET http://localhost:8080/book/1
Content-Type: application/json

###
GET http://localhost:8080/uk/page?current=1&size=4
Content-Type: application/json

###
POST http://localhost:8080/uk

###
POST http://localhost:8080/book
Content-Type: application/json

{
  "bookName": "计算机网络卷6",
  "bookType": 3,
  "bookAuthor": "mike"
}
###
GET http://localhost:8080/book/2/3
Content-Type: application/json
###
GET http://localhost:8080/book/1
Content-Type: application/json
###

