

spring:
  datasource:
    druid:
      username: wanqingying
      password: wanqingying
      url: jdbc:mysql://212.129.221.42:3306/jva?serverTimezone=UTC
      driver-class-name: com.mysql.cj.jdbc.Driver
  boot:
    admin:
      client:
        url: http://127.0.0.1:8005

logging:
  level:
    root: info
  group:
    sdu: wan.sdu.sp, wan.sdu.sp.api
#  file:
#    path: /Users/wanqingying/IdeaProjects/spa-book-ats/log
  config: classpath:logback-spring.xml

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl




management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

